language: objective-c
osx_image: xcode8.2

xcode_project: StackFlow.xcodeproj
xcode_scheme: StackFlow

before_install:
  - brew update
  - brew install python3
  - alias python=python3
  - alias pip=pip3
  - pip install virtualenv
  - gem install xcpretty

before_script:
  - virtualenv -p python3 --no-site-packages .venv
  - source .venv/bin/activate 
  - pip install -U pyobjc

script:
  - xcodebuild -project StackFlow.xcodeproj -list
  - xcodebuild -project StackFlow.xcodeproj -scheme StackFlow test | xcpretty
